name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
permissions:
  actions: read-all|write-all
  checks: read-all|write-all
  contents: read-all|write-all
  deployments: read-all|write-all
  id-token: read-all|write-all
  issues: read-all|write-all
  discussions: read-all|write-all
  packages: read-all|write-all
  pages: read-all|write-all
  pull-requests: read-all|write-all
  repository-projects: read-all|write-all
  security-events: read-all|write-all
  statuses: read-all|write-all
    
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
  
        with:
          github_user_name: yakiniats
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
